{% set name = "bt" %}
{% set version = "0.2.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d162d71aaaaf7265a848d1fc0040f503add32dac2f9f3127bece0d74c22efb9b 

build:
  number: 2
  script:
    - rm -rf bt/core.c  # [not win] remove cythonized file in sdist
    - rm -rf bt\core.c  # [win]
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython >=0.29.25                       # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - cython >=0.29.25
    - pip
  run:
    - python
    - ffn >=0.3.5
    - pyprind >=2.11
test:
  imports:
    - bt
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/pmorissette/bt
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'bt - flexible backtesting for Python'
  description: |
    bt - flexible backtesting for Python
  doc_url: http://pmorissette.github.io/bt/
  dev_url: https://github.com/pmorissette/bt

extra:
  recipe-maintainers:
    - timkpaine
