{% set name = "bt" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 201eb9a5723d9ca6426a6e96f7213ae9d2f5d2aa7934069fc466cc32dbf46b78

build:
  number: 1
  script:
    - rm -rf bt/core.c  # [not win] remove cythonized file in sdist
    - del "bt\core.c"  # [win]
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython >=0.29.25                       # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - cython >=0.29.25
    - pip
  run:
    - python
    - ffn >=1.1
    - pyprind >=2.11
    - tqdm >=4
test:
  imports:
    - bt
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/pmorissette/bt
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'bt - flexible backtesting for Python'
  description: |
    bt - flexible backtesting for Python
  doc_url: http://pmorissette.github.io/bt/
  dev_url: https://github.com/pmorissette/bt

extra:
  recipe-maintainers:
    - timkpaine
